parameters:
#    sopinet_flash_messages.example.class: Sopinet\FlashMessagesBundle\Example

services:
#    sopinet_flash_messages.example:
#        class: %sopinet_flash_messages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
