parameters:
#    sopinet_flash_messages.example.class: Sopinet\FlashMessagesBundle\Example

services:
    sopinet_flashMessages:
        class:        Sopinet\FlashMessagesBundle\Service\FlashNotifier
        arguments:
            entityManager: @doctrine.orm.entity_manager
            container: @service_container